### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rossman22590** [leap-ai/headshots-starter#12] opened 2023-09-19 22:45 UTC
Error: > Couldn't find a `pages` directory. Please create one under the project root
    at Object.findPagesDir (C:\Users\Ross\Desktop\RealChar\headshots-starter\node_modules\next\dist\lib\find-pages-dir.js:42:19)       
    at new DevServer (C:\Users\Ross\Desktop\RealChar\headshots-starter\node_modules\next\dist\server\dev\next-dev-server.js:107:66)    
    at NextServer.createServer (C:\Users\Ross\Desktop\RealChar\headshots-starter\node_modules\next\dist\server\next.js:137:20)
    at C:\Users\Ross\Desktop\RealChar\headshots-starter\node_modules\next\dist\server\next.js:149:42
    at async NextServer.prepare (C:\Users\Ross\Desktop\RealChar\headshots-starter\node_modules\next\dist\server\next.js:127:24)        
    at async C:\Users\Ross\Desktop\RealChar\headshots-starter\node_modules\next\dist\cli\next-dev.js:142:9

C:\Users\Ross\Deskto

**Comment by Marfuen** [comment] 2023-09-19 22:49
@rossman22590 Hi, what are the steps to reproduce this, also what package manager are you using and what version of next is in your package.json?

**Comment by rossman22590** [comment] 2023-09-19 22:55
using vercel     "next": "^13.5.1",
    "next-multipart": "^0.5.1",

**Comment by rossman22590** [comment] 2023-09-19 22:55
npm

**Comment by Marfuen** [comment] 2023-09-19 23:01
Can you provide the steps to reproduce this error?

**Comment by rossman22590** [comment] 2023-09-19 23:13
npm install npm run dev

**Comment by rossman22590** [comment] 2023-09-19 23:15
i will try again

**Comment by Marfuen** [comment] 2023-09-19 23:16
Yeah let me know, if not can you try using yarn?

**Comment by rossman22590** [comment] 2023-09-19 23:16
yes i can

**Comment by rossman22590** [comment] 2023-09-19 23:55
ok now it works but loggin in doesnt

**Comment by rossman22590** [comment] 2023-09-19 23:55
no error after email link I click it brings me home unlogged in

**Comment by rossman22590** [comment] 2023-09-20 00:01
ok i solved login now i ge this on train (node:36184) ExperimentalWarning: buffer.File is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
TypeError: Cannot read properties of undefined (reading 'map')
    at POST (webpack-internal:///(rsc)/./app/leap/train-model/route.ts:87:97)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\Ross\Desktop\RealChar\headshots-starter\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:1:66877

**Comment by rossman22590** [comment] 2023-09-20 00:01
i upload image and hit trian and get error

**Comment by ratracegrad** [comment] 2023-09-20 00:04
I had the same issue earlier today with the same errors. It was resolved by changing the version of nextjs in package.json. [See my issue for resolution](https://github.com/leap-ai/headshots-starter/issues/10)

**Comment by rossman22590** [comment] 2023-09-20 00:06
and on vercel i get this <html>
<body>


Error: MISSING NEXT_PUBLIC_SUPABASE_ANON_KEY!
--
20:06:12.642 | at 90791 (/vercel/path0/.next/server/app/leap/image-webhook/route.js:167:11)
20:06:12.642 | at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:43)
20:06:12.643 | at __webpack_exec__ (/vercel/path0/.next/server/app/leap/image-webhook/route.js:316:39)
20:06:12.643 | at /vercel/path0/.next/server/app/leap/image-webhook/route.js:317:74
20:06:12.643 | at __webpack_require__.X (/vercel/path0/.next/server/webpack-runtime.js:138:21)
20:06:12.643 | at /vercel/path0/.next/server/app/leap/image-webhook/route.js:317:47
20:06:12.643 | at Object.<anonymous> (/vercel/path0/.next/server/app/leap/image-webhook/route.js:320:3)
20:06:12.645 | at Module._compile (node:internal/modules/cjs/loader:1256:14)
20:06:12.645 | at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
20:06:12.645 | at Module.load (node:internal/modules/cjs/loader:1119:32)
20:06:12.649 |  
20:06:12.649 | > Build error occurred
20:06:12.654 | Error: Failed to collect page data for /leap/image-webhook
20:06:12.654 | at /vercel/path0/node_modules/next/dist/build/utils.js:1158:15
20:06:12.655 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
20:06:12.655 | type: 'Error'
20:06:12.656 | }
20:06:12.733 | error Command failed with exit code 1.
20:06:12.733 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
20:06:12.753 | Error: Command "yarn run build" exited with 1


</body>
</html>

**Comment by rossman22590** [comment] 2023-09-20 00:07
and its there

**Comment by rossman22590** [comment] 2023-09-20 00:18
ok anon key solved on vercel now , when i trian i get somehting went worng and here is log (node:8) ExperimentalWarning: buffer.File is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
{
  code: 'PGRST204',
  details: null,
  hint: null,
  message: "Column 'modelId' of relation 'models' does not exist"
}

**Comment by rossman22590** [comment] 2023-09-20 00:20
![PXL_20230920_001950824.MP.jpg](https://github.com/leap-ai/headshots-starter/assets/6137292/c42f2c07-c2ac-4081-94f9-9ca9fdee48e2)

**Comment by rossman22590** [comment] 2023-09-20 00:21
![PXL_20230920_001950824.MP.jpg](https://github.com/leap-ai/headshots-starter/assets/6137292/739ddcc8-2d23-4f41-aedf-3750747f7e32)

**Comment by rossman22590** [comment] 2023-09-20 00:26
can you provide a supabase schema maybe  something is wrong there.

**Comment by Marfuen** [comment] 2023-09-20 00:59
@rossman22590 It looks like you name modelId as modelid, maybe that's the issue?

**Comment by Marfuen** [comment] 2023-09-20 01:00
Like this
![image](https://github.com/leap-ai/headshots-starter/assets/30200426/108dfbef-264f-4f0c-9ef1-b00dbfdb81fc)

**Comment by rossman22590** [comment] 2023-09-20 01:04
Do you have a schema file im new to this it would really help me

**Comment by Marfuen** [comment] 2023-09-20 18:39
I don't think I can get a schema file from supabase, but the screenshot above shows you the tables you need, also in the readme you can also see the types and relations of each column and table

**Closed by Marfuen** 2023-09-20 18:39 UTC
